-- MySQL Script generated by MySQL Workbench
-- Tue Nov 24 12:45:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LoL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LoL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LoL` DEFAULT CHARACTER SET utf8 ;
USE `LoL` ;

-- -----------------------------------------------------
-- Table `LoL`.`main`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LoL`.`main` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastmean` INT NULL,
  `Mon` INT NULL,
  `Tue` INT NULL,
  `Wed` INT NULL,
  `Thi` INT NULL,
  `Fri` INT NULL,
  `Sat` INT NULL,
  `Sun` INT NULL,
  `sum` INT NULL,
  `mean` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
